# frozen_string_literal: true

# A sample is a single piece of data generated by an actor
class Sample < ApplicationRecord
  actable

  belongs_to :task
  belongs_to :actor

  attribute :actor_sig

  def actor_sig
    return 'GENERATED' if actor_id.zero?

    Actor.find(actor_id).actor_sig.split('-').first
  end

  def additional_info
    task = Task.where(id: task_id).first
    type = task.actable_type
    task = task.specific
    media = Medium.find(task.media_id)
    sample = specific
    { type: type, task: task, sample: sample, media: media }
  end
end
